### ISSUE TITLE
Implement the Hint page frontend part.

### ISSUE THREAD

**Issue by uparkalau** [bluewave-labs/bluewave-onboarding#128]
1. Use the predefined page: `frontend\src\scenes\hints\HintDefaultPage.jsx`.
2. Add a list of hints using mock data.
3. Implement an edit hint popup that popups up when the "Edit" button is clicked.
4. Create a hint form that appears after clicking the "Create a Hint" button.
5. The hint creation page is also the same as the edit hint page. When editing the hint, the header will read “Edit hint” instead of “New hint”

<img width="962" alt="Screenshot 2024-08-03 at 1 54 31 PM" src="https://github.com/user-attachments/assets/b2544692-52d4-4867-9212-9e4396b0aa5d">

Link to Figma file: https://www.figma.com/design/MLPbP1HM2L9ON6f88pHTee/Onboarding?node-id=601-3452&t=hr8l93I7nYDD0y5M-1

**Comment by gorkem-bwl** [comment]
@thomastepi the issue is updated with more comments and new screenshots. Also added a link to corresponding area in Figma file.
