### ISSUE TITLE
Get rid of the dashboard top banner

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-onboarding#153]
Currently the dashboard top banner is too high and consumes a lot of space. We can get rid of it by removing it completely, and make a few changes. 

Here is the sample screenshot showing it.

![Changes](https://github.com/user-attachments/assets/f46a9f25-49b7-4346-9af4-3e88fd912f38)

Changes: 

- Get rid of top banner
- Move user profile dropdown to bottom left
- Move the sidebar up to benefit from the space
- Move support link to the bottom of the sidebar menu

**Comment by Cihatata** [comment]
I can do it if there is no issue owner @gorkem-bwl

**Comment by gorkem-bwl** [comment]
Yes, please go ahead. Thank you.

**Comment by Cihatata** [comment]
Thank you @parthmanhas

**Comment by parthmanhas** [comment]
Welcome @Cihatata
