### ISSUE TITLE
Change Color Regex Logic

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#169]
Right now we only allow 6 character colors in the backend for popups and banners (like #000000). Change the logic to allow 3,4 and 8

**Comment by VishnuSrivatsava** [comment]
Hi @erenfn can I work on this issue?

**Comment by VishnuSrivatsava** [comment]
Also it is to be changed only in this file I suppose? 
[backend/src/controllers/popupController.js](https://github.com/bluewave-labs/bluewave-onboarding/blob/633e89b3b88956153406c6f6ed461af38a4da865/backend/src/controllers/popupController.js#L21)

**Comment by erenfn** [comment]
Work on the develop branch. There are 4 files to change:

2 controllers:

- backend/src/controllers/banner.controller.js 
- backend/src/controllers/popupController.js

2 models:

- backend/src/models/Banner.js
- backend/src/models/Popup.js

- [ ]  Create a guideHelpers.js in the backend utils folder, and refactor `validateColorCode` in controllers. (Remove validateColorCode in the controllers and use the one in the helpers)

```
// for controllers
const isValidHexColor = (value) => {
    const hexColorRegex = /^#([A-Fa-f0-9]{3}|[A-Fa-f0-9]{4}|[A-Fa-f0-9]{6}|[A-Fa-f0-9]{8})$/;
    return hexColorRegex.test(value);
};

// for models
const validateHexColor = (value, fieldName) => {
    if (!isValidHexColor(value)) {
        throw new Error(`${fieldName} must be a valid hex color code`);
    }
};
```

- [ ] Check color fields in the models. Example:

```
 fontColor: {
            type: DataTypes.STRING,
            allowNull: false,
            defaultValue: "#FFFFFF",
            validate: {
                isHexColor(value) {
                    validateHexColor(value, 'fontColor');
                },
            },
        },
```

**Comment by VishnuSrivatsava** [comment]
Just made a PR. Please check. Thanks.
