### ISSUE TITLE
Implement Toast Notifications for Create Activity Pages

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#172]
- [ ] Create a Toast Notification Component
![image](https://github.com/user-attachments/assets/23199bba-edbb-4ab9-b0a1-98460594665e)
@gorkem-bwl We also need to have 'Popup {id} is edited' notifications and an error notification like: 'Add Popup Error: Font Color should be a valid hexcode'

- Under src/scenes/popup and src/scenes/bannerPage:

- [ ] Replace console.log's in errors with toast errors.
- [ ] Display the relevant toast notification after adding/deleting/editing a popup/banner/hint etc. in their main page

- Under src/services

- [ ] Delete console.log's. You don't need to replace those with toast notifications.

**Comment by gorkem-bwl** [comment]
@erenfn sure, I'm on it and will be on Figma soon.

**Comment by gorkem-bwl** [comment]
@erenfn They are on Figma now.

<img width="570" alt="Screenshot 2024-08-29 at 12 13 46 PM" src="https://github.com/user-attachments/assets/480ed932-890c-49c6-8785-4cbedde765f2">

For easy copying: 
- You edited this popup
- Error adding popup: You need to provide a valid hexcode for the popup color

**Comment by Cihatata** [comment]
If you want, I can do this. @gorkem-bwl

**Comment by erenfn** [comment]
> If you want, I can do this. @gorkem-bwl

Sure. You can use a custom library like react-toastify or sonner to display these notifications

**Comment by gorkem-bwl** [comment]
> If you want, I can do this. @gorkem-bwl

Just make sure you check the Figma link in readme.md and build your toast designs mimicking/similar to the ones in the Figma design.

**Comment by uparkalau** [comment]
> If you want, I can do this. @gorkem-bwl

this is for local environment:
https://github.com/bluewave-labs/bluewave-onboarding/blob/master/.env

**Comment by gorkem-bwl** [comment]
That is for https://github.com/bluewave-labs/bluewave-onboarding/discussions/150 right?

**Comment by Cihatata** [comment]
I created PR -> https://github.com/bluewave-labs/bluewave-onboarding/pull/188
