### ISSUE TITLE
'Username already exists' error must be 'Email already exists'

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-onboarding#175]
When I try to create a new user on the system with a previous email that is registered, it shows 'Username already exists'. Instead of this error, we need to provide 'Email already exists' under the Email section. 

Here is a screenshot: 

<img width="446" alt="Screenshot 2024-09-02 at 2 18 15 AM" src="https://github.com/user-attachments/assets/1acceb2a-cfa4-4488-a1fa-f69714df14ec">

**Comment by mr-loop-1** [comment]
hello @gorkem-bwl , I am looking to contribute and would want to work on this issue. Can you assign this to me.

**Comment by mr-loop-1** [comment]
@gorkem-bwl

I raised a pr for the issue and there is another bug I found that is present in the app.

I found that there is a `unique` constraint on the `username` column too in the database model. Hence, if you change the email but keep the username that exists in database, then it would throw

![Screenshot from 2024-09-03 23-37-25](https://github.com/user-attachments/assets/701582b2-0f11-4943-bd4d-807f1412d28f)

which is not handled currently.

**Comment by gorkem-bwl** [comment]
@erenfn can you check when you have some time?

**Comment by mr-loop-1** [comment]
The login page doesn't have a "Login by username" option, which gave me the impression that username can be same for different emails, in which case the fix would be to simply remove the constraint.
But if it is intended to keep username unique, then username would have a separate error from backend.

@gorkem-bwl I would like to work on either case once decided and can add commits to this pr.

**Comment by mr-loop-1** [comment]
@gorkem-bwl so, it should not be unique since it is just name? should I add to this pr or keep it separate.

**Comment by gorkem-bwl** [comment]
Yes, no uniqueness required as it's just a name and surname.

**Comment by mr-loop-1** [comment]
thanks, I will raise a pr, would name and surname be two separate fields or just one full name field

**Comment by gorkem-bwl** [comment]
Let's make ıt separate.

**Comment by mr-loop-1** [comment]
@gorkem-bwl , I raised a pr and added some points to review in description. Look forward to feedback.
