### ISSUE TITLE
Sidebar should be stretched 100% to the bottom of the visible screen

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-onboarding#176]
Currently the sidebar is cut in the middle of the screen. It must be stretched to the bottom of the screen. 

Here is the screenshot: 

<img width="518" alt="Screenshot 2024-09-02 at 2 22 25 AM" src="https://github.com/user-attachments/assets/2cf2f943-60ec-413b-9c05-2be9deeef245">

**Comment by Cihatata** [comment]
https://github.com/bluewave-labs/bluewave-onboarding/pull/190

**Comment by wlanhage** [comment]
If this still is an issue, I can take a look at it. If so, please assign it to me! BR
