### ISSUE TITLE
Creating popup js code

### ISSUE THREAD

**Issue by swoopertr** [bluewave-labs/bluewave-onboarding#20]
### Issue: Implement Dynamic Popup Script Loading

- [x] Place the Script in the Directory

- Place the `popup.js` script inside the newly created `scripts` directory.
- **Path**: `src/scripts/popup.js`

- [x] Serve the Script from the Server

- Update the server code to serve the script from the `scripts` directory.

- [x] Update HTML to Load Script Dynamically

- Modify the HTML file to load the script dynamically using the API ID.

- [x] Test the Implementation

- Test the implementation to ensure the script is loaded dynamically and the popups are displayed correctly

**Comment by swoopertr** [comment]
Popup.js is generated and tested.
The structure is created for js files and loading time management.

**Comment by gorkemcetin** [comment]
What is the latest status for this task please? Thanks.

**Comment by swoopertr** [comment]
This can be closed. It is done.
There is a task which connection to the backend.

**Comment by swoopertr** [comment]
task completed
