### ISSUE TITLE
Applying CodeRabbit Suggestions before merging to master

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#208]
Applying CodeRabbit Suggestions on PR #177 before merging to master

**Comment by mr-loop-1** [comment]
I would like to work on this. Please assign me @erenfn

**Comment by erenfn** [comment]
> I would like to work on this. Please assign me @erenfn

@uparkalau assigned this task to himself. We have other issues that are not posted yet. Are you looking for frontend or backend?

**Comment by mr-loop-1** [comment]
Hi @erenfn , I would love to involve with the development of this project. 
I am fortunately fairly skilled in node, sql and react as well so either is good to me and had the opportunity to traverse through most code previously.

**Comment by uparkalau** [comment]
> Hi @erenfn , I would love to involve with the development of this project. I am fortunately fairly skilled in node, sql and react as well so either is good to me and had the opportunity to traverse through most code previously.

We can find other task for your. Would you prefer backend or frontend?

**Comment by mr-loop-1** [comment]
@erenfn backend would be good

**Comment by uparkalau** [comment]
> @uparkalau backend would be good

https://github.com/bluewave-labs/bluewave-onboarding/issues/210 you can work on this task
