### ISSUE TITLE
Refactor Popup&banner controller and Popup&banner models validations

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#227]
For example in Popup model we have 

>       closeButtonAction: {
>         type: DataTypes.STRING,
>         allowNull: false,
>         validate: {
>           isIn: [["no-action", "open-url", "close-popup", "open-url-new-tab"]],
>         },
>       },

and in Popup controller we have

> const validateCloseButtonAction = (value) => {
>   const validActions = [
>     "no-action",
>     "open-url",
>     "close-popup",
>     "open-url-new-tab",
>   ];
>   return validActions.includes(value);
> };

Refactor all these validations (for popups and banners) in util/popup.helper.js / util/banner.helper.js (You should create these files)

**Comment by prashant-80** [comment]
I can do this!

**Comment by gorkem-bwl** [comment]
Go ahead please :) 

FYI @SimerdeepSinghGrewal :)
