### ISSUE TITLE
Change static Avatar to dynamic

### ISSUE THREAD

**Issue by uparkalau** [bluewave-labs/bluewave-onboarding#235]
That static avatar image might not be the final. Consider makin' it dynamic.
frontend/src/components/Header/Header.jsx
<Avatar src={userInfo.avatarUrl || "/vendetta.png"} alt={userInfo.fullName} size="medium" />

![image](https://github.com/user-attachments/assets/39b45e02-e4e8-4b6d-97c3-9dd36890440a)

**Comment by erenfn** [comment]
We will change this once we have the image upload feature

**Comment by uparkalau** [comment]
> We will change this once we have the image upload feature

Sounds good , keep it in TODO
