### ISSUE TITLE
Refactor name, surname validation

### ISSUE THREAD

**Issue by uparkalau** [bluewave-labs/bluewave-onboarding#236]
frontend/src/scenes/login/CreateAccountPage.jsx
case 'name':
case 'surname':
  const isValid = value.trim().length > 0 && /^[a-zA-Z\s-]+$/.test(value);
  setValidation((prev) => ({ ...prev, [`is${name.charAt(0).toUpperCase() + name.slice(1)}Valid`]: isValid }));
  break;

**Comment by erenfn** [comment]
I think these are CodeRabbit suggestions. Can you provide more context?

**Comment by uparkalau** [comment]
> I think these are CodeRabbit suggestions. Can you provide more context;, what is the issue here?

Yes it is. We just have to add more validation. 

Names and surnames should only contain letters (both uppercase and lowercase) and possibly special characters like hyphens (-) or apostrophes (').
The minimum length could be set to 2 characters (to avoid single letter entries).
The maximum length can be set, e.g., 50 characters (to prevent overly long inputs).
You can enforce the first letter to be capitalized (optional).
