### ISSUE TITLE
Refactor Forgot Password Css

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#244]
Some styles may be already in Login.css. Double check it, and if possible make it a css module.

**Comment by erenfn** [comment]
![image](https://github.com/user-attachments/assets/52d7c1b9-94ff-4728-9897-2ab544b5c0d3)

take a look at the suggestion

**Comment by parthmanhas** [comment]
Hi @erenfn, fixed in #248
