### ISSUE TITLE
When refreshing we see the Login page until the token is verified

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#247]
This should not happen. We need to find a way to avoid showing the Login Page while loading.

**Comment by mr-loop-1** [comment]
I too noticed this when working. Just checked the files, and I can take this up.

**Comment by erenfn** [comment]
Sure, I'll assign it to you

**Comment by prashant-80** [comment]
I can do this if it's not done yet!

**Comment by gorkem-bwl** [comment]
Let's wait for @mr-loop-1 for this one.
