### ISSUE TITLE
Left Menu isn't fully visible on every screen size

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#249]
![image](https://github.com/user-attachments/assets/66916082-8615-4fb2-a784-01fd924eef87)

The profile isn't fully visible on my viewport height (650px). Write media queries to fit the `LeftMenu` component to various screen sizes. For smaller screens, the gaps between buttons can be reduced, and the font size can be changed from 13px to 12px if necessary.

**Comment by CodeJr10** [comment]
Lemme check

**Comment by prashant-80** [comment]
Hi,I'd like to work on this issue

**Comment by gorkem-bwl** [comment]
> Hi,I'd like to work on this issue

Sure, Prashant! Thanks.

**Comment by prashant-80** [comment]
@erenfn  @gorkem-bwl  I have fixed the issue

**Comment by gorkem-bwl** [comment]
Great, thanks Prashant! Can you send a screenshot here?

**Comment by prashant-80** [comment]
here is the updated screenshots
<img width="1407" alt="Screenshot 2024-10-03 at 5 07 52 PM" src="https://github.com/user-attachments/assets/b2bea233-8884-4f0a-bbc4-bcfab99871e2">
<img width="1432" alt="Screenshot 2024-10-03 at 5 07 26 PM" src="https://github.com/user-attachments/assets/c49e6c4b-95ca-4477-9a9f-a08e9dc96595">
