### ISSUE TITLE
Node.js.yml fix

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#255]
![image](https://github.com/user-attachments/assets/786d47f9-d394-4545-b379-26836211a22c)
![Ekran görüntüsü 2024-09-29 232230](https://github.com/user-attachments/assets/f8bac99f-2ca2-4e06-b376-e3d938d5ee65)

Take a look at the sugggestion

**Comment by uparkalau** [comment]
it is in develop branch
