### ISSUE TITLE
Refactor Data Validations in backend controllers

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#271]
Refactor Data Validations in backend controllers. There are some repetitive code there. Using express-validator is an option

**Comment by mr-loop-1** [comment]
Thanks. I can take this up. Will try to keep up with settings branch depending on sequence of merge.

**Comment by eulerbutcooler** [comment]
Can i take this issue up? recently have applied express validator in a mini project of mine i think i can do it

**Comment by erenfn** [comment]
Hi! Thanks for your interest. @mr-loop-1 is currently assigned to the issue, so please reach out to him to see if you can collaborate or if he would like to hand it over. I'm fine with either of you taking it on.

**Comment by erenfn** [comment]
@mr-loop-1 ?

**Comment by mr-loop-1** [comment]
Sure @eulerbutcooler you are good to go. Raise your pr against the develop branch and I will add the necessary.

**Comment by eulerbutcooler** [comment]
> Sure @eulerbutcooler you are good to go. Raise your pr against the develop branch and I will add the necessary.

Thank you! I'll update soon

**Comment by eulerbutcooler** [comment]
Hey I've refactored the code and made separate files for checking the validations for some of the controllers. Should i put them in utilis folder or should i include them in the controller file itself? @erenfn @mr-loop-1

**Comment by eulerbutcooler** [comment]
Sure! Just did it #284

**Comment by eulerbutcooler** [comment]
Here #285 @uparkalau

**Comment by uparkalau** [comment]
> Here #285 @uparkalau 

Fork a new branch from the develop branch. Create PR into develop.

**Comment by eulerbutcooler** [comment]
#287  I think this does it. @uparkalau
