### ISSUE TITLE
Settings Page features

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#277]
![image](https://github.com/user-attachments/assets/c166ff02-542b-48cc-88d6-3bcabcd82b06)
![image](https://github.com/user-attachments/assets/0cd86ba7-0dd4-42c2-b2af-eebeba2073c3)

- [ ] Implement inline editing for organization name when clicked the pencil button
- [ ] Create invite new member popup when user clicks 'invite team member'
- [ ] Create delete account popup when user clicks 'delete account'
- [ ] Create upload image popup when user clicks 'update'

settings page will be under src/scenes/settings when #276 is merged

**Comment by parthmanhas** [comment]
Hi @erenfn, raised a PR here #280
