### ISSUE TITLE
Store user profile pictures

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#278]
- [ ] add additional field into user table to store user profile pictures
- [ ] Create CRUD endpoints for profile pictures

![image](https://github.com/user-attachments/assets/e1354c6a-b0c8-47c6-bc33-bdaa69268da9)

**Comment by gorkem-bwl** [comment]
Looks good! We can also use a default avatar image based on user's name first letters. I believe MUI has this option.

**Comment by d02ev** [comment]
Hi, I would like to contribute on this issue. I just needed some help setting up the app locally and running it, also regarding profile picture upload what is the service you are using to handle it, like Google Cloud/AWS/Firebase/ Supabase etc. I apologize for any inconvenience, I am an absolute beginner in contributing.

**Comment by erenfn** [comment]
We are using AWS to host our server, so probably using S3 would be better. To run the code, simply execute 'docker compose up' from the root folder.

**Comment by parthmanhas** [comment]
Hi @erenfn , raised a PR here #279
