### ISSUE TITLE
Disable the login button in the LoginPage and the signup button in the SignupPage while the user clicks it and a loader is visible.

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#281]
Disable the login button in the LoginPage and the signup button in the SignupPage while the user clicks it and a loader is visible.

Similar to #261

**Comment by NohaFahmi** [comment]
Hi @erenfn,  can I work on this issue, please? if so, kindly assign it on me.

**Comment by erenfn** [comment]
Sure
