### ISSUE TITLE
Move mui-root stylings in various css files to src/assets/theme.jsx 

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#288]
For example in src/components/HeadingTabs/Tabs.css we have:

```
.MuiTab-root {
    font-family: 'Inter', sans-serif;
    font-size: 13px;
    font-style: normal;
    font-weight: 400;
    line-height: 20px;
  }
```

We should move this styling into theme.jsx

Develop branch is our most up-to-date branch, so work on the develop branch.

**Comment by HarshTripathi1103** [comment]
can u assign me this work ?

**Comment by erenfn** [comment]
Sure

**Comment by erenfn** [comment]
@HarshTripathi1103 Hey, how is this going?

**Comment by Bugbuster2004** [comment]
can u assign me this issue?

**Comment by erenfn** [comment]
Sure

**Comment by Bugbuster2004** [comment]
Hello,
I recently raised a pull request addressing the issue of migrating MUI-specific styles into `theme.jsx`. Could you kindly review it and confirm whether it meets the expected standards or requires any modifications?  

Looking forward to your feedback.  

Best regards,

**Comment by Bugbuster2004** [comment]
hey @erenfn any updates on my PR so far?

**Comment by mantosh-mariner** [comment]
would you assign to me this issue

**Comment by Shivamxeric** [comment]
can u assign me these work

**Comment by Tushnik1** [comment]
Is this issue resolved?
Because, I was looking into it and worked out the issue.
Would, Love to contribute to it.

**Comment by erenfn** [comment]
Hey, thanks for your interest. Its PR is currently under review. But feel free to look at other issues!
