### ISSUE TITLE
Refactor popup button actions to an enum

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#291]
Refactor popup button actions to an enum

in PopupComponent.jsx
```
  const handleButtonClick = () => {
    if (buttonAction === 'close the popup') {
      handleClose();
    } else if (buttonAction === 'open url') {
      window.open(actionButtonUrl, '_self'); 
    } else if (buttonAction === 'open url in new page') {
      window.open(actionButtonUrl, '_blank'); 
    }
  };
```

In PopupContent.jsx

```
  <DropdownList 
      actions={['No action', 'Open URL', 'Open URL in a new tab']} 
      onActionChange={handleActionChange}
      selectedActionString={buttonAction}
  />
```

Also we need to change it in the backend

**Comment by NohaFahmi** [comment]
Hi @erenfn, can I work on this?

**Comment by erenfn** [comment]
Right now, for Popups, Banners, and Hints, we store these values as strings like 'close the popup'. A better approach might be to store them as their enum numbers, like 1, 2, or 3. @uparkalau, what do you think?

If we plan to use the same enum for both the backend and frontend, create a 'shared' folder in the root directory and add the enums there (either as a JavaScript file or a JSON file). Although they may seem similar, create a separate enum for each table.

**Comment by NohaFahmi** [comment]
Hi @erenfn, I checked the code and I have a question,
you've mentioned in the description this method:
in PopupComponent.jsx

`const handleButtonClick = () => {
    if (buttonAction === 'close the popup') {
      handleClose();
    } else if (buttonAction === 'open url') {
      window.open(actionButtonUrl, '_self'); 
    } else if (buttonAction === 'open url in new page') {
      window.open(actionButtonUrl, '_blank'); 
    }
  };`
  
I can't find a component named PopupComponent.jsx, but there is folder for popup components including the content, preview and appearance components, so do you mean that this method should be added on the preview component? when user preview the popup, the action button should be working as per action selected by user, correct?

**Comment by erenfn** [comment]
Can you pull from develop again? I think that component is merged now
