### ISSUE TITLE
Implement Settings Services in the frontend to connect to the backend.

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#292]
@mr-loop-1 Settings Page is ready. Now we have to call those endpoints in the frontend

![image](https://github.com/user-attachments/assets/3e9a7343-2526-4ae5-bcea-ae6c84c119b1)

**Comment by mr-loop-1** [comment]
Sure. I can take this up.

**Comment by mr-loop-1** [comment]
Many tables like banners, tours and popuplog don't have migrations?

**Comment by erenfn** [comment]
We'll have to create another issue for that, but sync will solve it, and aren't they irrelevant to this issue?

**Comment by mr-loop-1** [comment]
The team row is created in migration, using sync force is truncating that table and removing our team row. Also, I checked the docs and they also say this feature is not for production https://sequelize.org/docs/v7/models/model-synchronization/

**Comment by uparkalau** [comment]
> Many tables like banners, tours and popuplog don't have migrations?
These tables are generated by the models. We are using migrations now because they will be needed for future production releases. For now, we simply erase the database after each build. Creating migrations is not mandatory at this stage, but it helps establish a pattern for the developers.

**Comment by erenfn** [comment]
> Many tables like banners, tours and popuplog don't have migrations?

I created issue #309 for this. We will not use `sync({ force: true })` in production. However, it is a useful tool for testing purposes. If you don't want to reboot your database, you can also use `sequelize.sync()`, which `'creates new tables according to the schema specified in the model,'` until issue #309 is implemented. But as I mentioned, for this issue, you probably will not need those tables.
