### ISSUE TITLE
The Search icon 🔍 is visible throughout at an off position 

### ISSUE THREAD

**Issue by ramanand-rv** [bluewave-labs/bluewave-onboarding#294]
**Describe the bug**
The Search icon is weirdly visible on the landing page and is visible throughout the page. It is present at a weird position and on click it simply reloads the page.

**To Reproduce**
1. Go to 'https://bluewavelabs.ca/'
2. Observe the Search icon 🔍
3. Scroll down to bottom of the page
4. Click on the Search icon 🔍

**Expected behavior**
It should be located in the navbar to be visible throughout. And on click it should not simply refresh the page instead take input.

**Screenshots**
![{579A5671-D54A-4BDD-8C28-1EF7C8B6DC00}](https://github.com/user-attachments/assets/22e91156-2c30-42a6-8964-c9f84df6ee10)

**Desktop (please complete the following information):**
 - Browser [Chrome, Brave, Edge]

**Comment by gorkem-bwl** [comment]
Thanks @ramanand-rv - will fix this.
