### ISSUE TITLE
Google doc link in CONTRIBUTING.md is incorrect

### ISSUE THREAD

**Issue by ramanand-rv** [bluewave-labs/bluewave-onboarding#295]
**Describe the bug**

**To Reproduce**
1. Go to https://github.com/bluewave-labs/bluewave-onboarding/blob/6461c9281e3a95c0d361fdce01136b8395936a56/CONTRIBUTING.md?plain=1#L101
2. Follow the link

**Expected behavior**
It should have opened the doc

**Screenshots**
![{7DB4B336-EF33-4224-9661-96622C1503C5}](https://github.com/user-attachments/assets/3d1ddf83-17cb-4144-9923-aefa2fc6b3bb)

![{DF7B6FAE-20D9-4CD5-BC3A-3D240AB448D4}](https://github.com/user-attachments/assets/1b292624-f6a1-41ea-a020-487544c0948f)

**Desktop (please complete the following information):**
 - Browser [e.g. Chrome, Safari, Brave, Edge]

**Comment by gorkem-bwl** [comment]
Thanks, fixed in https://github.com/bluewave-labs/bluewave-onboarding/commit/f13355b23fb143a7c1b059b1954055311af5e5cb
