### ISSUE TITLE
Change the fetch functions for popup, banner and hint in frontend

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#301]
- [ ] Change the fetch functions for popups, banners, and hints to retrieve all of the organization's items instead of just the user's items. For example, in `frontend/src/services/popupServices`, change the fetch endpoint from `popup/popups` to `popup/all_popups`.

- [ ]  Add `accessGuard.middleware` to the add, edit, and delete routes for popups, banners, and hints. This ensures that only admins can access these endpoints.

- [ ] After adding the middleware, update the frontend: Make the create, edit, and delete buttons in the `Popup/Banner/Hint Default Page ` (they are under `frontend/src/scenes`) render conditionally based on the user's role. These buttons should only be visible if the user is an admin. User's role can be fetched via `authProvider.jsx`

- [ ] Test the UI for both admins and members and include the screenshots in your PR. For members you may need to first send an invite to an email and then login.

Work on the develop branch

**Comment by d02ev** [comment]
Hi @erenfn, 
I would like to work on this issue. Please assign it to me.

**Comment by erenfn** [comment]
Sure! I assigned it to you

**Comment by d02ev** [comment]
All the other routes for example in `popups` such as `/popups` and `/get_popup/:id` except for the `/all_popups` should have a `accessGuard.middleware` added to them ? and this goes same for `banners` and `hints` ?

**Comment by erenfn** [comment]
We should not be using accessGuard.middleware on any `GET` endpoints. The logic is that members can only view the popups, not add or modify them

**Comment by d02ev** [comment]
Suppose, If an admin hasn't created any banner, popup or hints. What should the member see in the `DefaultPage`? Since they cannot create them ?

**Comment by erenfn** [comment]
We can leave it as it is right now. Just disabling the 'create' button for members is fine

**Comment by d02ev** [comment]
#337
