### ISSUE TITLE
First User Register Steps

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#303]
- [ ] After the first user (admin) registers, it should be directed to '/progress-steps' page, and after these steps are done, this page should no longer be visible to anyone.
- [ ] Use team/invite endpoint to send invites in the first page 
![image](https://github.com/user-attachments/assets/f1e4c04e-08c3-4f2d-a6a5-c6ed13e401d8)

- [ ] Create an endpoint in the backend to set the organisation name and use it in the third progress-steps page
![image](https://github.com/user-attachments/assets/9eb02aa9-524b-4eab-b2a9-d327f652d03a)

Work on the develop branch

**Comment by d02ev** [comment]
Should the organisation name be saved in the db? If yes, then should there be a different model or an extra field within the user model?

**Comment by erenfn** [comment]
Yes, it should be saved in the db. Check the develop branch -this is our most up-to-date branch. We have 'team' table there which includes the organisation name

**Comment by d02ev** [comment]
I want to work on this issue can you please assign it to me?

**Comment by d02ev** [comment]
Hi @erenfn,
There are certain doubts regarding the 3rd point. I studied the code base and found that there are already routes defined to add and fetch organisation name from the backend.

**Comment by erenfn** [comment]
I don't remember having a 'set organization' route, but I may have overlooked that. In that case, just use that endpoint in the frontend; you don't have to create one for the backend.

**Comment by d02ev** [comment]
`const getTeamDetails = async (req, res) =>   try {
    const data = await teamService.getTeam();
    if (!data || !data.team || !data.users) {
      throw new Error("Team data not found");
    }
    const result = {
        name: data.team.name,
        users: data.users.map((user)=> ({
            name: user.name,
            email: user.email,
            role: settings.user.roleName[user.role]
        })),
    }
    return res.status(200).json(result);
  } catch (err) {
    const { statusCode, payload } = internalServerError(
      "GET_TEAM_ERROR",
      err.message,
    );
    res.status(statusCode).json(payload);
  }
};

const updateTeamDetails = async (req, res) => {
    const userId = req.user.id;
    const { name } = req.body;
    try {
      await teamService.updateTeam(userId, name);
      return res.status(200).json({ message: "Team Details Updated Successfully" });
    } catch (err) {
      const { statusCode, payload } = internalServerError(
        "UPDATE_TEAM_ERROR",
        err.message,
      );
      res.status(statusCode).json(payload);
    }
};`

These are the 2 controllers I am talking about.

**Comment by erenfn** [comment]
The updateTeamDetails endpoint is for 'editing' and is a PUT request. We need to create a POST request to add the organization name. Although the implementation will be very similar, it is better to follow REST API conventions.

**Comment by d02ev** [comment]
Hi @erenfn, I have certain doubts regarding the tasks
1. "After the first user (admin) registers, it should be directed to '/progress-steps' page, and after these steps are done, this page should be visible again to anybody." What do you mean by "visible again to anybody" ?
2. "Use team/invite endpoint to send invites in the first page". Should there be a 'Submit' or 'Send Invites' button right next to the input box, to send the invites or should it be handled by the 'Next' button itself?
3. "Create an endpoint in the backend to set the organisation name and use it in the third progress-steps page". Similarly should there be a 'Submit' or 'Set Org Name' button right next to the input name or should it be handled by the 'Next' button ?

**Comment by erenfn** [comment]
1. Thank you for pointing that out is should be 'should **not** be visible'
2. Those endpoints should be called when the user completes progress-steps in the 4th page by clicking 'Sweet!'
![image](https://github.com/user-attachments/assets/9d5a9a15-0b70-4744-ae90-d7a917040465)

- Also since this is the first user logging in, there is no team yet. By that 'POST' request, I mean creating an endpoint to create a team with the specified name. Also, be sure to add a check in the controller to prevent the creation of more than one team.

**Comment by d02ev** [comment]
Hi @erenfn
Please take a look at my latest PR for this issue and let me know if there needs to be certain changes.
#322

**Comment by d02ev** [comment]
Hi @erenfn,

I have left some comments on your reviews please take a look and let me know what needs to be done ahead.

**Comment by erenfn** [comment]
Hey @d02ev, I can't see your comments

**Comment by d02ev** [comment]
Np, I'll post them here.

1. This is for the review on the removal of the navigate() in the progress steps:
"The handler method sendInvitesAndSetOrgName() handles the saving of invites and org name into the db. The 'Sweet' button contains, the necessary navigation to the home page already."

2. For the validation rule you said to use, I have already applied those changes.

**Comment by erenfn** [comment]
I get 
![image](https://github.com/user-attachments/assets/cd451e3d-a09e-4d8d-a60e-0a468bfccfd0)

After I click 'Sweet'. Did it work on your end?

**Comment by d02ev** [comment]
Yep it worked on my end. I pushed the code after testing.

**Comment by d02ev** [comment]
I am deleting my #322 PR as I've had some issues fetching latest changes from develop branch. I'll be creating a new PR with the reviewed changes and refactorings/

**Comment by d02ev** [comment]
Hey @erenfn,
#327 is my new PR including changes recommended by you.

**Comment by d02ev** [comment]
Hey @erenfn,
Can you see my latest comment on the PR ?
