### ISSUE TITLE
Create Migrations for these tables: Banners, Popuplog, Hints, and Tours

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#309]
Create migrations in backend/migrations for 

- [ ] Banner
- [ ] PopupLog
- [ ] Hint
- [ ] Tour

tables that are already implemented.

**Comment by jaykayudo** [comment]
Hi @erenfn, Could i be assigned this?

**Comment by erenfn** [comment]
Sure

**Comment by jaykayudo** [comment]
@erenfn i can't seem to find a `hint` and `tour` table

**Comment by erenfn** [comment]
We are working on the develop branch

**Comment by jaykayudo** [comment]
@erenfn  I have made a PR.
