### ISSUE TITLE
Convert in-page designs to modals

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-onboarding#311]
While creating a popup, tour, hint or banner, the dialog used shouldn't be embedded to the page, but should be a modal instead. The popup should have a fixed width.

<img width="1071" alt="image" src="https://github.com/user-attachments/assets/0e06e308-31ca-482f-b2c9-2c12d98e23aa">

**Comment by erenfn** [comment]
It seems like a big issue so please implement this in a separate PR

**Comment by erenfn** [comment]
#401
