### ISSUE TITLE
Toast.id type warning

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#315]
`Warning: Failed prop type: Invalid prop `toast.id` of type `string` supplied to `ToastItem`, expected `number`. `

We sometimes encounter this warning. Changing the type from number to string doesn't resolve the issue, as we then receive a similar error: 'got number, expected string'.

 

- [ ] Identify where the problem occurs (check how we supply toast.id) and resolve the warning.

**Comment by akshikrm** [comment]
I would like to work on this issue, can you please assign this to me
