### ISSUE TITLE
Write some tests for backend using Vitest

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#316]
- Setups vitest for backend
- Write tests for the existing endpoints in the backend. We don't expect you to write tests for every endpoint, but please choose one series of endpoints (e.g., Popup endpoints) and write tests for them.

**Comment by PoorShawn** [comment]
Hi, @erenfn ! I'm new to open source. Can I be assigned to this ? It may take a few days.
