### ISSUE TITLE
Update Profile Image

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#324]
- [ ] After you click 'update' in upload image popup, the popup should be closed.
- [ ] After you refresh the page, the uploaded image reverts back to the placeholder image. Check the implementation of how we send the image to backend and how we retrieve it

This page is in scenes/Settings/ProfileTab

![image](https://github.com/user-attachments/assets/9b0a48a6-580e-40e5-bbd4-b2ccc83c1620)

- Work on the develop branch

**Comment by aryanp-86** [comment]
Hello @erenfn , I would like to work on this issue.

**Comment by erenfn** [comment]
Sure, I'll assign it to you

**Comment by aryanp-86** [comment]
Hi @erenfn , I have raised a PR with the fixes. Would you please review it once. Thanks.
