### ISSUE TITLE
 Configure path aliases in frontend

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#326]
- [ ] Configure path aliases in your build setup:

```
// vite.config.js or similar
{
  resolve: {
    alias: {
      '@components': '/src/components'
    }
  }
}
```

- [ ] Then update the imports like

from `import ColorTextField from '../../../../components/ColorTextField/ColorTextField';`
to `import ColorTextField from '@components/ColorTextField/ColorTextField';`

- Work on the develop branch

**Comment by aryanp-86** [comment]
Hello @erenfn , I would like to work on this issue.

**Comment by erenfn** [comment]
Sure, I'll assign it to you

**Comment by aryanp-86** [comment]
@erenfn 
I have raised a PR with the changes. Will you please review it once. Thanks.
