### ISSUE TITLE
BE: API key & code snippet

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-onboarding#332]
That complements #331 

- [ ] Add fields to the Team table for the Server URL.
- [ ] Create endpoints to store and modify Server URL.
- [ ] Call these services on that page.

![image](https://github.com/user-attachments/assets/a4dbd56a-5e1c-4965-8c18-886a1cb5239f)

**Comment by d02ev** [comment]
Hi @erenfn and @gorkem-bwl,
I would like to work on this issue. Please assign it to me.

**Comment by gorkem-bwl** [comment]
Assigned to you @d02ev - thanks!

**Comment by d02ev** [comment]
Are there any BE validations for `API_KEY` and `SERVER_URL`?

**Comment by erenfn** [comment]
You can skip that for now. Also #340 (its frontend) is now merged

**Comment by d02ev** [comment]
Hi @erenfn, I have some business logic queries:
1. Is the `API_KEY` and `SERVER_URL` saved together in the DB ? or It can be anyone at a time ?
2. For now, I have kept these columns as `nullable` in the DB. Is this fine ?

**Comment by erenfn** [comment]
1- Single endpoint to store all of them
2-Yes

**Comment by d02ev** [comment]
Please review #345 for this issue.

**Comment by d02ev** [comment]
Please review #347 which is similar to #345, which I had to close due to some branch rebasing issues.

**Comment by mantosh-mariner** [comment]
Hi, I’m Mantosh , and I’m interested in contributing to this project. I came across issue and would like to work on it. Could you please assign it to me?

Thank you for your time and for maintaining this project. Looking forward to your reply!

**Comment by d02ev** [comment]
> Hi, I’m Mantosh , and I’m interested in contributing to this project. I came across issue and would like to work on it. Could you please assign it to me?
> 
> Thank you for your time and for maintaining this project. Looking forward to your reply!

Hi Mantosh, this issue has already been assigned to me. Look for the issues that are unassigned.
