### ISSUE TITLE
Edit Popup, Banner does not work

### ISSUE THREAD

**Issue by uparkalau** [bluewave-labs/bluewave-onboarding#334]
1. Add a new banner or popup and try to edit it. You will see an error indicating that the data you are trying to change did not save.

![image](https://github.com/user-attachments/assets/f955ae83-17a3-47aa-9c77-c75612c44035)

- [ ] Expectation: During the edit process, I should be able to save new data into the database.

**Comment by akshikrm** [comment]
Hello, has this issue been fixed, when I tried to update a banner there was no problem. I was hoping to work on this.

<img width="1442" alt="Screenshot 2024-10-31 at 21 44 15" src="https://github.com/user-attachments/assets/afff65f7-9f8f-4070-b988-f61b934f7463">
<img width="359" alt="Screenshot 2024-10-31 at 21 44 22" src="https://github.com/user-attachments/assets/cd0b9edc-1880-4beb-9158-86ee396771f4">

**Comment by erenfn** [comment]
The issue is on 'develop' branch.
