### ISSUE TITLE
Settings RBAC

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#338]
- [ ] Create a helper function to check role based authentications
- [ ] Refactor changes made in #337 such as `{role === 'admin' && <ParagraphCSS />}` to use this function. 
- [ ] Team and API Key options in settings page should be only visible to the admins not members

![image](https://github.com/user-attachments/assets/703b312a-c069-4ab8-92cb-bc84c33fcad8)
![image](https://github.com/user-attachments/assets/ccdd8959-1825-4e7c-9834-597e19f417fc)

**Comment by aryanp-86** [comment]
Hi @erenfn 
I would like to work on this issue

**Comment by erenfn** [comment]
Sure, I assigned it to you
