### ISSUE TITLE
Register Page Modifications

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#339]
- [ ]  Modify CreateAccountPage.jsx to include necessary fields for admin registration (this will only happen once).

- [ ] Set the register page as the initial page when there are no users.

When the server is first launched and no users exist (you can use getTeamCount service to check this), the first person (admin) who opens the application should see the admin registration page, as shown below:

![image](https://github.com/user-attachments/assets/fa3e4f6c-5e5f-4849-a79b-684f30e83390)

Currently, users are redirected to the login page, which should not happen for the first registering user.

Our registration page currently looks like this:

![image](https://github.com/user-attachments/assets/e2db58e8-7bac-4639-b086-1bc2727f0d97)

It should be modified for this scenario, one time only.

**Comment by d02ev** [comment]
Hi @erenfn,

I would like to work on this issue. Please assign it to me.

**Comment by erenfn** [comment]
Sure! I assigned it to you.

**Comment by d02ev** [comment]
Hi @erenfn,

Regarding the routing to `/login` or `/register`, to fetch if any team exists, the user must be authenticated and this routing is before a user is registered or logged in. How should I handle this ? Is it feasible to make the `/count` endpoint unguarded ?

**Comment by erenfn** [comment]
Yes, you can remove the authentication for /count endpoint

**Comment by d02ev** [comment]
Hi @erenfn,
Please review #343 for this issue.

**Comment by d02ev** [comment]
@erenfn can you please elaborate more on https://github.com/bluewave-labs/bluewave-onboarding/pull/343#discussion_r1836881236
