### ISSUE TITLE
CustomTextField width fix

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#341]
Add a feature to` CustomTextField` to allow it to stretch to 100% width. Currently, we do not handle its width well.

**Comment by PranitiV** [comment]
Hi! I'm looking to contribute to this open source project. Is this issue fixed?

**Comment by erenfn** [comment]
It's not fixed yet. You can go ahead

**Comment by saksham-malhotra-27** [comment]
Hey Devs! I worked on this feature, so feel free to check it out if everything looks good.

**Comment by saksham-malhotra-27** [comment]
Hi @erenfn ,
This is my first ever contribution to open source, and I'm really excited about it! If you have any feedback regarding my commits or the way I wrote the code, I would greatly appreciate it. It would help me learn and improve.
Thank you for your time!

**Comment by mantosh-mariner** [comment]
Hi, I’m Mantosh , and I’m interested in contributing to this project. I came across issue  and would like to work on it. Could you please assign it to me?

Thank you for your time and for maintaining this project. Looking forward to your reply!

**Comment by saksham-malhotra-27** [comment]
Hey @mantosh-mariner , I’ve already submitted a pull request for this issue. If @erenfn and @thomastepi approve it, it can be merged. Just wanted to inform you since I have already worked on and completed the same issue.

**Comment by saksham-malhotra-27** [comment]
Hey @erenfn,  just wanted to check if there are any updates on the PR?

**Comment by saksham-malhotra-27** [comment]
Hey @erenfn ! Any updates on the PR? If any changes are needed, please let me know, and I'll take another look.

**Comment by saksham-malhotra-27** [comment]
Thank you for merging this one !
