### ISSUE TITLE
Helper link add/edit screen

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-onboarding#352]
I have modified the screen a bit to make sure helper links can be added or edited. 

Here is the screenshot, and the corresponding [Figma file is here](https://www.figma.com/design/MLPbP1HM2L9ON6f88pHTee/Onboarding?node-id=601-3692&t=swniQuoERIAKIhjZ-1).

<img width="1058" alt="image" src="https://github.com/user-attachments/assets/e91b91e8-3d7d-4c0c-86ed-261f534c8c96">

**Comment by erenfn** [comment]
#401
