### ISSUE TITLE
Implement Transactions to Migrations and Database Services

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#358]
- Implement transactions to existing migrations -for both up and down
- Implement transactions for services under backend/src/service folder that modify the database

**Comment by aryanp-86** [comment]
Hello @erenfn , I would like to work on this issue.

**Comment by erenfn** [comment]
Sure, I'll assign it to you

**Comment by erenfn** [comment]
Hey @aryanp-86, any updates?

**Comment by aryanp-86** [comment]
Almost there.Will raise a PR in a day or two
