### ISSUE TITLE
Updated Hints page

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-onboarding#361]
Previously a Hint could be assigned to an .element, but there were no mentions of the URL that this .element could be in. The new design introduces a URL section where the .element should be present.

Also please update the backend and create a new migration accordingly.

Here is the new screenshot (note the new target element URL):

![image](https://github.com/user-attachments/assets/f53ba168-f09b-488b-abb1-f417736ef402)

Here is the corresponding Figma file: https://www.figma.com/design/MLPbP1HM2L9ON6f88pHTee/Onboarding?node-id=1397-3912&t=cxKQwC2d9LyAMLWT-1

**Comment by erenfn** [comment]
#401
