### ISSUE TITLE
Preview popup shows the content in a scrollbar

### ISSUE THREAD

**Issue by bolatein** [bluewave-labs/bluewave-onboarding#369]
When the content for the popup is more than 3 lines, the preview shows it with a scrollbar. It should be showing the whole content without limiting the box height with a scrollbar. 

<img width="1435" alt="Screenshot 2024-12-10 at 14 03 49" src="https://github.com/user-attachments/assets/83287da2-ee8b-47c0-b68c-faefc78b7629">

**Comment by erenfn** [comment]
solved in #401
