### ISSUE TITLE
Action buttons misplaced

### ISSUE THREAD

**Issue by bolatein** [bluewave-labs/bluewave-onboarding#370]
Cancel and Save buttons misplaced for the below. 
<img width="1435" alt="Screenshot 2024-12-10 at 14 05 23" src="https://github.com/user-attachments/assets/46f47147-ef38-4e1a-a970-6b46d844657f">

--

Correct placement should be like the below.
<img width="1435" alt="Screenshot 2024-12-10 at 14 05 21" src="https://github.com/user-attachments/assets/b3361229-e147-4cbb-9acd-e780d92d6bc7">

**Comment by gorkem-bwl** [comment]
Assigned.
