### ISSUE TITLE
Misplaced tooltip/popup

### ISSUE THREAD

**Issue by bolatein** [bluewave-labs/bluewave-onboarding#371]
The tooltip/popup saying "You edited this banner" is misplaced as it's shown on top right. Instead, it should be bottom right.

<img width="1435" alt="Screenshot 2024-12-10 at 14 32 59" src="https://github.com/user-attachments/assets/b99d82bd-d5b0-4ae6-9a61-9466699cb848">

**Comment by MandeepPaul** [comment]
Should the change apply only to the 'You edited this banner' popup, or should it be implemented for all popups in the application?

**Comment by gorkem-bwl** [comment]
> Should the change apply only to the 'You edited this banner' popup, or should it be implemented for all popups in the application?

Should be implemented for all popups in the application, possibly in the components section.
