### ISSUE TITLE
Size of text in a text box is small 

### ISSUE THREAD

**Issue by bolatein** [bluewave-labs/bluewave-onboarding#372]
As the title says, the text in the shown textbox is small. It should be as the others (I guess it's 13 px).
 
<img width="1435" alt="Screenshot 2024-12-10 at 14 41 59" src="https://github.com/user-attachments/assets/3b29c5e1-fa75-49e3-8b1d-26bf6890c0a9">

**Comment by INDHU1402** [comment]
Hey @bolatein
I came across this issue and would like to work on resolving it, can you assign it to me ?

**Comment by bolatein** [comment]
Sure! Assigned.

**Comment by INDHU1402** [comment]
PS: Accidentally raised #383 PR hence closed it, so please ignore :)

**Comment by INDHU1402** [comment]
@erenfn @bolatein Any reason behind closing the PR https://github.com/bluewave-labs/bluewave-onboarding/pull/384 without reviewing or merging the changes ?

**Comment by erenfn** [comment]
> @erenfn @bolatein Any reason behind closing the PR #384 without reviewing or merging the changes ?

Changing a global variable wasn't the correct solution. Since this is a local discrepancy, you needed to change it in its CSS file. #401

Fixed in #401
