### ISSUE TITLE
Statistics for the Statistic cards

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#380]
- [x] Add endpoints to backend to fetch statistics for the statistic cards. 
- The stats should be calculated using the guide log entries. 
- By 'this month,' we mean the last 30 days, and 'last month' refers to the period between 60 and 31 days ago.
- If the views of any guide in the last month is 0, the percentage increase is N/A

- [x] Call those endpoints in the frontend to show statistics

![image](https://github.com/user-attachments/assets/cc9fec9f-8f40-45c6-a31e-2e54a734b4ca)

**Comment by swoopertr** [comment]
related table should be indexed.
