### ISSUE TITLE
Sidebar item should be highlighted when I am inside a page

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-onboarding#409]
When I click on a sidebar item, that area should be highlighted for a visual cue. Highlight color can be the same as the hover color.

<img width="493" alt="image" src="https://github.com/user-attachments/assets/1042833c-535e-4eed-9a53-717c2a423575" />

**Comment by Tushnik1** [comment]
Hi, @gorkem-bwl 
I would love to work on this issue.
Could you please assign it to me?

**Comment by Tushnik1** [comment]
![Screenshot 2024-12-21 210427](https://github.com/user-attachments/assets/87f55104-a9e6-464d-a61b-5d1a522fa572)

Solved the issue of highlighting the selected menu option, it will look like this.

**Comment by gorkem-bwl** [comment]
> Solved the issue of highlighting the selected menu option, it will look like this.

Is this the same color as the hover color?

**Comment by Tushnik1** [comment]
Yes,

**Comment by Tushnik1** [comment]
Shall I proceed to make a PR request?

**Comment by bolatein** [comment]
@Tushnik1 Please only change the background color of the selected menu item (to the same color while hovering). Keep the others (letter formating etc.) as they are. 

See the refeence image below. 

<img width="264" alt="Screenshot 2024-12-21 at 23 00 30" src="https://github.com/user-attachments/assets/c0335033-431e-4a42-9911-08f6e8e64260" />

**Comment by Tushnik1** [comment]
Okk, I did the required changes. 👍 
![Screenshot 2024-12-22 014439](https://github.com/user-attachments/assets/199d8b3f-b855-4bef-9ef1-c24a461173f5)

Please let me know if it is okk or something is required to be changed.

**Comment by bolatein** [comment]
@Tushnik1 Thanks for your contribution. We decided to proceed with some other design development. So, I'll assign this to the internal team.

**Comment by Tushnik1** [comment]
@bolatein Okk
