### ISSUE TITLE
Text editor buttons should be highlighted when selected

### ISSUE THREAD

**Issue by bolatein** [bluewave-labs/bluewave-onboarding#415]
When any button in the editor is selected, it should be highlighted (with the same color while hovering) until the selected text unselected.

For example, in the below image, the selected text is bold and italic, therefore the bold and italic button should be highlighted unless the user selects another text.
<img width="799" alt="Screenshot 2024-12-21 at 23 28 41" src="https://github.com/user-attachments/assets/2ae109f7-2335-48d5-acf4-f510bff37060" />

**Comment by Shaikh-Mudassir** [comment]
I can work on it and solve this bug. Please assign me the issue

**Comment by gorkem-bwl** [comment]
Thanks Shaikh, assigned.

**Comment by erenfn** [comment]
@bolatein @gorkem-bwl Can you check if UI in this PR looks good?

https://github.com/bluewave-labs/bluewave-onboarding/pull/419
