### ISSUE TITLE
Blocked aria-hidden on an element because its descendant retained focus. 

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#422]
When you open and close the dialog (Create Banner/Popup/Hints/Link page) this error occurs in the console This shouldn't happen

> Blocked aria-hidden on an element because its descendant retained focus. The focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.
> Element with focus: button
> Ancestor with aria-hidden:  <div id=​"root">​flex<div class=​"container">​…​</div>​flex<div class=​"_toastContainer_fmpzi_2">​</div>​flex</div>​

![image](https://github.com/user-attachments/assets/d60d05c6-148e-46aa-ad07-1202bd49bbed)

**Comment by 3looy-hubs** [comment]
Hey, @erenfn I would like to be assigned to this issue

**Comment by erenfn** [comment]
Sure, I'll assign it to you

**Comment by 3looy-hubs** [comment]
hey @erenfn, requested a PR

**Comment by erenfn** [comment]
Hey, I merged it. Everything looks good. Thanks

**Comment by 3looy-hubs** [comment]
happy to help
