### ISSUE TITLE
Refactor Logos Component to Make it Reusable

### ISSUE THREAD

**Issue by uparkalau** [bluewave-labs/bluewave-onboarding#50]
We need to refactor the existing Logos component to make it reusable for our application. Currently, the Logos component has hardcoded values. Implement props to increase flexibility.

- [x] Create the branch from develop branch for this issue, use exactly the name as the issue title to link it. @SevinjFeyzi 
- [x] Update the Logos component to accept props for the logo sources, alt text, and additional styles or classes.
> props example `key={index} src={src} alt={altText} className='logoImage'`
- [x] Make sure the component can handle a dynamic list of logos.
- [x] Make sure the existing styles in LogosStyles.css are applied correctly and update if necessary to support the new prop-based structure.
- [x] Implement PropTypes: "see the Switch component as an example"
- [x] Test the Component:
> Create a test parent component to verify the new Logos component works as expected with different props.
> Ensure the component renders the logos correctly.

**Comment by gorkemcetin** [comment]
For this one, please implement the onboarding logo and not the hrm app logo.
