### ISSUE TITLE
Fix Auth migrations and auth controller

### ISSUE THREAD

**Issue by erenfn** [bluewave-labs/bluewave-onboarding#63]
- change updated_at to updatedAt in create_users)table migration
- Change { User }to User in auth controller imports.

These were causing problems when I tried to call the auth endpoints. The problems are gone with these fixes.

**Comment by uparkalau** [comment]
The issue resolved into Issue 63: fixed issue 63 and added createdBy to popup table #64

**Comment by uparkalau** [comment]
Closed and moved to #64
