### ISSUE TITLE
Create Progress steps pages 

### ISSUE THREAD

**Issue by uparkalau** [bluewave-labs/bluewave-onboarding#94]
Use Progress steps component to implement steps logic into the app.

https://www.figma.com/design/MLPbP1HM2L9ON6f88pHTee/User-onboarding?node-id=0-1&t=Uo6tfNoVU4LpoJf6-0
![image](https://github.com/bluewave-labs/bluewave-onboarding/assets/132397574/cd839063-cdb9-46c3-8f72-ebeea22dc9c5)

**Comment by gorkem-bwl** [comment]
@erenfn can we remove and/or hide this page for now? It will be implemented later, so there is no need to show this page for now as we don't have a Chrome plugin yet.

**Comment by uparkalau** [comment]
> @erenfn can we remove and/or hide this page for now? It will be implemented later, so there is no need to show this page for now as we don't have a Chrome plugin yet.
We can leave it as it is. We will implement backend functionality later.
